name: oauth1
version: 2.0.0
description: '"RFC 5849: The OAuth 1.0 Protocol" client implementation for Dart.'
homepage: https://github.com/nbspou/dart-oauth1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crypto: ^3.0.0
  http: ^1.2.1
  uuid: ^3.0.7

dev_dependencies:
  test: ^1.16.5
